sudo: false
language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.10"
script: npm test
branches:
  only:
    - master
    - /^v[0-9]/
deploy:
  provider: npm
  email: 'public@erikdesjardins.io'
  api_key:
    secure: mwx6zWO1WlDJLI5nQR7ayXguk6tPqORhBm8VBQUkDpVaW81kkqVldoe/W6HLrc9TJ38jlKU5Lvm3mlNT89H4pCqq1ahb6No32aP8OzTtj+QsBkSx+JwwN3HlD4wZHWhKHbC7Vz3OtVluAu/+3kn/URVviGsnThxFdmQjBdKqth+KUfSBltro00VO/PtJz9FnW+9OJAVGufrL2+FWzjkBYZRBdqmaJO6wsdzOg+fpSR2ECHa5HmsY9N937ZF5lH/Br3FgKKWF6u6GyvbVCL/xIrTObnTFXZSrQa3vpEOphRtlhVzd6mtY2NAyCWofXOe+GIFYok0A+ZCUgOvxmGSkVCDTWupJqa+rqZQTWU1nPzsH8XhTbRw9Lyq6Q/fFzhHOZVvsZJX+fXtKLocZk2K1p/PxMv77jGeZEgtQcZG5Wzc3argC9MkGeDO2N61je+EsfX39qtjE56XFJfY6ClpjPkpNiLHkIBqF5YLB+kNWTphOxpgJfMV5iMc1tWW2gApqkCgQCzleXDBwwfY3Pyv8QjRcXBi+EG2CK8zii8n97DQ0W3NfzH9PFDQ6eloHS6aj+aFKUzxU/P3dsaMRrdKt453kGAuFsyznlbV6xlOpBi+3uRL3m/vxpY/cAbHem7aYbX+i+c3kFKJYiegwddg7tr4Pkb8l4xw0Q0G9WVKyMW0=
  on:
    tags: true
    node: 5
